WebApplication1/Models/Card.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Data.Sql;
using System.Data.SqlClient;
using System.Net;
using System.IO;
using System.Net.Http;
using System.Collections;

namespace DuelTerminal.Models
{
	public class Card
	{
		public string API { get; set; }
		public string Status { get; set; }
		public string Name { get; set; }
		public string CardType { get; set; }
		public string Text { get; set; }
		public string Attribute { get; set; }
		public string Type { get; set; }
		public int Attack { get; set; }
		public int Defense { get; set; }
		public int Level { get; set; }
		public string ImageUrl { get; set; }
		public string Property { get; set; }
		public object Image { get; set; }
		


		//constructor
		public Card(string name)
		{
			//access API Data String 
			string url = "https://private-anon-6faa03cb86-yugiohprices.apiary-proxy.com/api/card_data/" + name;
			WebClient client = new WebClient();
			string urlString = client.DownloadString(url);

			//get rid of curly brackets in this string 
			urlString = ReplaceCurly(urlString);

			//split 
			ArrayList key = Split(urlString);

			//return string 
			string splitUrl = "";


			//split and remove the quotations then add into the arraylist 
		
			//assign attributes 
			if (key.Contains("status")){
				int index = key.IndexOf("status") + 1;
				this.Status = key[index].ToString();
			}

			if (key.Contains("name"))
			{
				int index = key.IndexOf("name") + 1;
				this.Name = key[index].ToString();
			}

			if (key.Contains("text"))
			{
				int index = key.IndexOf("text") + 1;
				this.Text = key[index].ToString();
			}

			if (key.Contains("card_type"))
			{
				int index = key.IndexOf("card_type") + 1;
				this.CardType = key[index].ToString();
			}

			if (key.Contains("type"))
			{
				int index = key.IndexOf("type") + 1;
				this.Type = key[index].ToString();
			}
			if (key.Contains("family"))
			{
				int index = key.IndexOf("family") + 1;
				this.Attribute = key[index].ToString();
			}

			if (key.Contains("atk") && key[key.IndexOf("atk") +1].ToString() != "null")
			{
				int index = key.IndexOf("atk") + 1;
				this.Attack = Int32.Parse(key[index].ToString());
			}
			if (key.Contains("def") && key[key.IndexOf("def") + 1].ToString() != "null")
			{
				int index = key.IndexOf("def") + 1;
				this.Defense = Int32.Parse(key[index].ToString());
			}
			if (key.Contains("level") && key[key.IndexOf("level") + 1].ToString() != "null")
			{
				int index = key.IndexOf("level") + 1;
				this.Level = Int32.Parse(key[index].ToString());
			}
			if (key.Contains("property"))
			{
				int index = key.IndexOf("property") + 1;
				this.Property = key[index].ToString();
			}

			//print out the array list of data 
			foreach (var item3 in key)
			{
				splitUrl = splitUrl + " " + item3;
			}
			urlString = splitUrl;
		}

		
		

		public String ReplaceCurly(String urlString)
		{
			urlString = urlString.Replace("{", string.Empty);
			urlString = urlString.Replace("}", string.Empty);
			return urlString;
		}

		public ArrayList Split(string urlString)
		{
			ArrayList key = new ArrayList();
			foreach (string item in SplitString(urlString))
			{

				foreach (string item2 in SplitString2(item))
				{

					String noQuotes = item2.Replace("\"", string.Empty);
					key.Add(noQuotes);
				}
			}
			return key;
		}

		public Array SplitString(string urlString)
		{
			return urlString.Split(','); 

		}
		public Array SplitString2(string item)
		{
			return item.Split(':');
		}


	
	} 
}

WebApplication1/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DuelTerminal.Models;
using System.Data.SqlClient;


namespace WebApplication1.Controllers
{
    public class CardController : Controller
    {
        // GET: Card
        public ActionResult Index()
        {
            return View();
        }

		public ActionResult UpdateDataBase()
		{
			//SqlCommand cmd;
			SqlConnection con;
			//SqlDataAdapter da;

			con = new SqlConnection(@"Data Source=BAR-JKPTPC2\SQLEXPRESS;Initial Catalog=CardDb;Integrated Security=True");
			con.Open();
			
			//access excel sheet of card names 
			//Excel.Application xlApp = new Excel.Application();
			//Excel.Workbook xlWorkbook = xlApp.Workbooks.Open(@"C:\Users\jaredb\OneDrive\Documents\Duel Terminal Project\yugiohdatabase.xlsx");
			//Excel._Worksheet xlWorksheet = (Excel._Worksheet)xlWorkbook.Sheets[1];
			//Excel.Range xlRange = xlWorksheet.UsedRange;

			//int rowCount = xlRange.Rows.Count;

			//for (int i = 1; i <= rowCount; i++)//for each name in list
			{
				//if card exists in DB then next card 
				//else create card with name
				/*Card newCard = new Card(xlRange.Cells[1,i].Value.ToString());
				Console.Write(newCard.Name);
				Console.Write(newCard.Status);
				Console.Write(newCard.Text);
				Console.Write(newCard.Type);
				Console.Write(newCard.CardType);
				Console.Write(newCard.Attack);
				Console.Write(newCard.Defense);
				Console.Write(newCard.Attribute);
				Console.Write(newCard.Level);
				//add to database
				cmd = new SqlCommand("INSERT INTO Cards (Name,Status,Text,CardType,Type,Attribute,Attack,Defense,Lv,Image,Image_Url) VALUES (@Name, @Status, @Text, @CardType, @Type, @Attribute, @Attack, @Defense, @Lv, @Image, @Image_Url)", con);
				cmd.Parameters.AddWithValue("@Name", newCard.Name);
				cmd.Parameters.AddWithValue("@Status", newCard.Status);
				cmd.Parameters.AddWithValue("@Text", newCard.Text);
				cmd.Parameters.AddWithValue("@CardType", newCard.CardType);
				cmd.Parameters.AddWithValue("@Type", newCard.Type);
				cmd.Parameters.AddWithValue("@Attribute", newCard.Attribute);
				cmd.Parameters.AddWithValue("@Attack", newCard.Attack);
				cmd.Parameters.AddWithValue("@Defense", newCard.Defense);
				cmd.Parameters.AddWithValue("@Lv", newCard.Level);
				cmd.Parameters.AddWithValue("@Image", newCard.Image);
				cmd.Parameters.AddWithValue("@Image_Url", newCard.ImageUrl);
				cmd.ExecuteNonQuery();
			
		*/
}

			return View();
		}
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Duel()
        {
            return View();
        }
        public ActionResult Search()
        {
			
            return View();
        }
        public ActionResult MyCollection()
        {
            return View();
        }
        public ActionResult DeckEditor()
        {
            return View();
        }
        public ActionResult MyAccount()
        {
            return View();
        }
        public ActionResult CreateMatch()
        {
            return View();
        }
        public ActionResult JoinMatch()
        {
            return View();
        }
        public ActionResult FindFriends()
        {
            return View();
        }
        public ActionResult DuelField()
        {
            return View();
        }
		public void UpdateDataBase()
		{

		}
    }
}

WebApplication1/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DuelTerminal.Models;

namespace WebApplication1.Controllers
{
    public class TestController : Controller
    {
        public String Index()
        {
			Card test = new Card("Trap Hole");
			return test.Status + System.Environment.NewLine + test.Name + System.Environment.NewLine + test.Text + System.Environment.NewLine + test.CardType + System.Environment.NewLine + test.Type + System.Environment.NewLine + test.Attribute + System.Environment.NewLine + test.Attack + System.Environment.NewLine + test.Defense + System.Environment.NewLine + test.Level + System.Environment.NewLine + test.Property;
			//return test.UrlString;
        }

		public ActionResult Test1()
		{
			return View();
		}
	}
}

WebApplication1/Views/Card/UpdateDataBase.cshtml
@{
    ViewBag.Title = "UpdateDataBase";
}

<h2>UpdateDataBase</h2>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/CreateMatch.cshtml
@{
    ViewBag.Title = "CreateMatch";
}
<style>
	.btn-back {
		font-size: 12px;
		width: 50px;
		height: 25px;
		margin: 0 auto;
		padding: 0;
		display: table-cell;
		vertical-align: middle;
		text-align: center;
	}
</style>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
		<p class="container"><a href='@Url.Action("Index","Home")' class="btn-back btn-primary btn-lg">&laquo; Back</a></p>
        <h1>Duel Creation</h1>
        <fieldset>
            <legend>Duel Mutator</legend>
            <p>
                <label>Life Points.......................................</label>
                <select id="LifePoints">
                    <option style="display: none;" selected hidden>8000</option>
                    <option value="1">1000</option>
                    <option value="2">2000</option>
                    <option value="3">3000</option>
                    <option value="4">4000</option>
                    <option value="5">5000</option>
                    <option value="6">6000</option>
                    <option value="7">7000</option>
                    <option value="8">8000</option>
                    <option value="9">9000</option>
                    <option value="10">10000</option>
                </select>
            </p>
            <p>
                <label>Maximum Number of Turns.................</label>
                <select id="Turns">
                    <option style="display: none;" selected hidden>99</option>
                    <option value="1">10</option>
                    <option value="2">20</option>
                    <option value="3">30</option>
                    <option value="4">40</option>
                    <option value="5">50</option>
                    <option value="6">60</option>
                    <option value="7">70</option>
                    <option value="8">80</option>
                    <option value="9">90</option>
                    <option value="10">99</option>
                </select>
            </p>
            <p>
                <label>Allow Banned Cards..........................</label>
                <select id="Banned">
                    <option style="display: none;" selected hidden>No</option>
                    <option value="1">Yes</option>
                    <option value="2">No</option>
                </select>
            </p>
            <p style="text-align:center"><a style="width:250px" href='@Url.Action("DuelField","Home")' class="btn btn-primary btn-lg">Start Duel &raquo;</a></p>
        </fieldset>
    </div>
</asp:Content>

WebApplication1/Views/Home/DeckEditor.cshtml
@{
    ViewBag.Title = "DeckEditor";
}
<style>
	.btn-back {
		font-size: 12px;
		width: 50px;
		height: 25px;
		margin: 0 auto;
		padding: 0;
		display: table-cell;
		vertical-align: middle;
		text-align: center;
	}
</style>

<div style="text-align:center" class="jumbotron container">
	<p class="container"><a href='@Url.Action("Index","Home")' class="btn-back btn-primary btn-lg">&laquo; Back</a></p>
	<h2>DeckEditor</h2>

</div>

WebApplication1/Views/Home/Duel.cshtml
@{
    ViewBag.Title = "Duel";
}
<style>

	.menu-button{
		text-align:center;
	}
	.btn{
		width:250px;
	}
	.container {
		text-align: left;
	}
	.btn-back {
		font-size: 12px;
		width: 50px;
		height: 25px; 
		margin: 0 auto;
		padding: 0;
		display: table-cell;
		vertical-align:middle;
		text-align:center;
		
	}


</style>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
		<p class="container" ><a href='@Url.Action("Index","Home")' class="btn-back btn-primary btn-lg">&laquo; Back</a></p>
        <h1 style="text-align:center">Dueling Terminal</h1>
       
        <p class="menu-button"><a href='@Url.Action("CreateMatch","Home")' class="btn btn-primary btn-lg">Create Match &raquo;</a></p>
        <p class="menu-button"><a href='@Url.Action("JoinMatch","Home")' class="btn btn-primary btn-lg">Join Match &raquo;</a></p>
        <p class="menu-button"><a href='@Url.Action("FindFriends","Home")' class="btn btn-primary btn-lg">Find Friends &raquo;</a></p>
    </div>

</asp:Content>

WebApplication1/Views/Home/DuelField.cshtml
@{
    ViewBag.Title = "DuelField";
}
<style>
    .SpellCardZone {
        display: inline-block;
        outline: solid;
        width: 100px;
        height: 100px;
        margin: 0px;
    }

    .CardStack {
        display: inline-block;
        outline: solid;
        width: 74px;
        height: 100px;
        margin: 0px;
    }


    .jumbotron {
        width: 100%;
        text-align: center;
        display: inline-block;
        white-space: nowrap;
    }

    .row {
        font-size: 0px;
    }

    .ScoreBoard {
        outline: solid;
        width: 648px;
        height: 40px;
        display: inline-block;
        font-size: 0;
    }

    .thumbnail {
        height: 100px;
        display: table;
    }

    .thumbnail img {
        height: 100%;
        width: 74%;
        display: table-cell;
        vertical-align: middle;
    }
</style>



<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <div class="row">
            <div class="CardStack"></div>
            <div class="SpellCardZone" ></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="CardStack"></div>
        </div>
        <div class="row">
            <div class="CardStack"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="CardStack"></div>
        </div>
        <div class="row">
            <div class="ScoreBoard">
            </div>
        </div>
        <div class="row">
            <div class="CardStack"></div>
			<div class="SpellCardZone"></div>
			<div class="SpellCardZone"></div>
            <div class="SpellCardZone">
                <a href="#" class="thumbnail">
                    <img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041">
                </a>
            </div>
            
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="CardStack"></div>
        </div>
        <div class="row">
            <div class="CardStack"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="SpellCardZone"></div>
            <div class="CardStack"></div>
        </div>
        <div title="placeholder" style="width:74px;height:100px">

        </div>
    </div>

</asp:Content>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<p></p>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <h1 style="text-align:center">Dueling Terminal</h1>

        <p style="text-align:center"><a style="width:250px" href='@Url.Action("Duel","Home")' class="btn btn-primary btn-lg">Duel &raquo;</a></p>
        <p style="text-align:center"><a style="width:250px" href='@Url.Action("Search","Home")' class="btn btn-primary btn-lg">Search &raquo;</a></p>
        <p style="text-align:center"><a style="width:250px" href='@Url.Action("MyCollection","Home")' class="btn btn-primary btn-lg">My Collection &raquo;</a></p>
        <p style="text-align:center"><a style="width:250px" href='@Url.Action("DeckEditor","Home")' class="btn btn-primary btn-lg">Edit Decks &raquo;</a></p>
        <p style="text-align:center"><a style="width:250px" href='@Url.Action("MyAccount","Home")' class="btn btn-primary btn-lg">My Account &raquo;</a></p>
    </div>

</asp:Content>
   

WebApplication1/Views/Home/MyAccount.cshtml
@{
    ViewBag.Title = "MyAccount";
}

<style>
	.btn-back {
		font-size: 12px;
		width: 50px;
		height: 25px;
		margin: 0 auto;
		padding: 0;
		display: table-cell;
		vertical-align: middle;
		text-align: center;
	}
</style>

<div style="text-align:center" class="jumbotron container">
	<p class="container"><a href='@Url.Action("Index","Home")' class="btn-back btn-primary btn-lg">&laquo; Back</a></p>
	<h2>My Account</h2>
</div>

WebApplication1/Views/Home/MyCollection.cshtml
@{
	ViewBag.Title = "MyCollection";
}
<style>
	.btn-back {
		font-size: 12px;
		width: 50px;
		height: 25px;
		margin: 0 auto;
		padding: 0;
		display: table-cell;
		vertical-align: middle;
		text-align: center;
	}

	div.gallery {
		margin: 5px;
		border: 1px solid #ccc;
		float: left;
		width: 180px;
	}

		div.gallery:hover {
			border: 1px solid #777;
		}

		div.gallery img {
			width: 100%;
			height: auto;
		}
</style>

<div style="text-align:center" class="jumbotron container">
	<p class="container"><a href='@Url.Action("Index","Home")' class="btn-back btn-primary btn-lg">&laquo; Back</a></p>
	<h2>MyCollection</h2>
	<div>
		<input type="text" name="search" placeholder="Search..">
	</div>

	<div>
		<div class="gallery">
			<a>
				<script>
					card1 = new Card();
				</script>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>
		</div>
	</div>
</div>

WebApplication1/Views/Home/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<style>
	input[type=text] {
		width: 130px;
		-webkit-transition: width 0.4s ease-in-out;
		transition: width 0.4s ease-in-out;
	}

		/* When the input field gets focus, change its width to 100% */
		input[type=text]:focus {
			width: 100%;
		}
	.jumbotron{
		
	}
	div.gallery {
		margin: 5px;
		border: 1px solid #ccc;
		float: left;
		width: 180px;
	}

		div.gallery:hover {
			border: 1px solid #777;
		}

		div.gallery img {
			width: 100%;
			height: auto;
		}

	div.desc {
		padding: 15px;
		text-align: center;
	}
	.btn-back {
		font-size: 12px;
		width: 50px;
		height: 25px;
		margin: 0 auto;
		padding: 0;
		display: table-cell;
		vertical-align: middle;
		text-align: center;
	}
</style>



<div class="jumbotron container">
	<p class="container"><a href='@Url.Action("Index","Home")' class="btn-back btn-primary btn-lg">&laquo; Back</a></p>

	<p class="container"><a href='@Url.Action("Test1","Test")' class="btn-back btn-primary btn-lg">&laquo; Test</a></p>


	<p class="container">
		<asp:Button ID="update" runat="server" OnClick="UpdateDataBase" />

		<a href='@Url.Action("UpdateDataBase","Card")' ID="update" class="btn-back btn-primary btn-lg">&laquo; Update Database</a>
	</p>



	<h2>Search</h2>
	<div>
		<input type="text" name="search" placeholder="Search..">
	</div>
	
	<div>
		<div class="gallery">
			<a>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>
			
		</div>

		<div class="gallery">
			<a>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>
			
		</div>

		<div class="gallery">
			<a>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>
			
		</div>

		<div class="gallery">
			<a>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>
			
		</div>
		<div class="gallery">
			<a>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>

		</div>
		<div class="gallery">
			<a>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>

		</div>
		<div class="gallery">
			<a>
				<img src="https://vignette2.wikia.nocookie.net/yugioh/images/d/d4/BlueEyesWhiteDragon-DUSA-EN-UR-1E.png/revision/latest?cb=20170330172041" width="300" height="200">
			</a>

		</div>
	</div>
</div>

WebApplication1/Views/Home/SystemSettings.cshtml
@{
    ViewBag.Title = "SystemSettings";
}

<h2>SystemSettings</h2>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dueling Terminal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dueling Terminal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dueling Terminal</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Test/Test1.cshtml
<h2>Test1</h2>

<form action="/action_page.php">
	First name: <input type="text" name="FirstName" value="Card Name"><br>
	
	<input type="submit" value="Submit">
</form>
<p>

</p>
<p>
	<a href='@Url.Action("Index","Test")' ID="test" class="btn-back btn-primary btn-lg">&laquo; Test</a>
</p>